# Arithmetic operators perform basic operation
# (+,-,*,/,%,**,//)
x=int(input("Enter first value:-"))
y=int(input("Enter second value:-"))
print("Addition=",x+y)
print("Substraction=",x-y)
print("Multiplication=",x*y)
print("Division=",x/y)
print("Moduls:-",x%y)
print("Floor division=",x//y)